# Note: This workflow is disabled for automatic runs to avoid redundancy.
# The primary formatting workflow is .github/workflows/format.yml
# You can still run this manually via the Actions tab if needed.
name: Auto Format with Black (manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black (apply fixes)
        run: black .

      - name: Commit & Push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format code with Black [skip ci]"
          branch: ${{ github.ref_name }}
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
