name: Auto Format with Black

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write  # allow committing back to the repository

jobs:
  format:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # use GITHUB_TOKEN for pushing

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black (apply fixes)
        run: black .

      - name: Commit & Push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format code with Black [skip ci]"
          branch: ${{ github.ref_name }}
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
