name: Format Code

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  format:
    name: Format with Black
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
    
    - name: Check formatting with Black
      id: black
      continue-on-error: true
      run: |
        # Vérifier le formatage
        black --check .
        
    - name: Commit changes if formatting is needed
      if: steps.black.outcome == 'failure'
      run: |
        # Formater le code
        black .
        
        # Configurer Git
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Créer un commit avec les changements
        git add .
        git diff-index --quiet HEAD || git commit -m "style: format code with Black [skip ci]"
        git push
