name: Format Code

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    name: Format with Black
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
    
    # On push: auto-fix and auto-commit using the GitHub token
    - name: Run Black (apply fixes)
      if: github.event_name == 'push' && github.actor != 'github-actions[bot]'
      run: black .
    
    - name: Commit & Push if changed
      if: github.event_name == 'push' && github.actor != 'github-actions[bot]'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: format code with Black [skip ci]"
        branch: ${{ github.ref_name }}
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
    
    # On PR: check-only (no push), fail if not formatted
    - name: Check formatting with Black (PR only)
      if: github.event_name == 'pull_request'
      run: black --check .
