name: Notifications

on:
  workflow_run:
    workflows: ["Python CI/CD"]
    types:
      - completed

jobs:
  notify-failure:
    if: >
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0]
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.workflow_run.pull_requests[0].number,
                body: `❌ **Échec du build**
                
                Le workflow **${{ github.event.workflow_run.name }}** a échoué pour cette PR.
                
                **Détails :**
                - Workflow : ${{ github.event.workflow_run.name }}
                - Exécution : [${{ github.run_id }}](${{ github.event.workflow_run.html_url }})
                - Commit : [${context.sha.slice(0, 7)}](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/commit/${context.sha})
                
                Consultez les logs pour plus de détails.`
              });
            } catch (error) {
              console.error('Erreur lors de la création du commentaire :', error);
            }
