name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        echo "=== Installing System Dependencies ==="
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            python3-dev \
            xvfb \
            libxcb-xinerama0 \
            libxcb-cursor0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-shape0 \
            libxcb-xfixes0 \
            libxcb-xkb1 \
            libglx0 \
            libopengl0 \
            libegl1 \
            libxkbcommon-x11-0 \
            libxcb-util1
    
    - name: Install PyQt6 and dependencies
      run: |
        echo "=== Installing PyQt6 ==="
        python -m pip install --upgrade pip
        pip install PyQt6 PyQt6-Qt6 PyQt6-sip
        pip install -r requirements.txt
    
    - name: Verify PyQt6 installation
      run: |
        echo "=== Verifying PyQt6 Installation ==="
        python -c "from PyQt6.QtCore import QT_VERSION_STR; print(f'PyQt6 Qt version: {QT_VERSION_STR}')"
    
    - name: Install package in development mode
      run: |
        echo "=== Installing package in development mode ==="
        pip install -e .
    
    - name: Run basic tests
      run: |
        echo "=== Running Basic Tests ==="
        export DISPLAY=:99.0
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        python -c "from PyQt6.QtWidgets import QApplication; app = QApplication([]); print('PyQt6 QApplication created successfully')"
    
    - name: Run pytest
      run: |
        echo "=== Running pytest ==="
        pip install pytest pytest-qt
        python -m pytest tests/ -v
