name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install system dependencies
      run: |
        echo "=== Installing System Dependencies ==="
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            python3-dev \
            xvfb \
            libxcb-xinerama0 \
            libxcb-cursor0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-shape0 \
            libxcb-xfixes0 \
            libxcb-xkb1
    
    - name: Install package in development mode
      run: |
        echo "=== Installing Package in Development Mode ==="
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run tests
      run: |
        echo "=== Running Tests ==="
        export DISPLAY=:99.0
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        
        # Run basic tests
        python -c "
        import sys
        print('Python version:', sys.version)
        print('Python path:', sys.path)
        
        # Test PyQt6 import
        try:
            import PyQt6
            print('PyQt6 version:', PyQt6.QtCore.QT_VERSION_STR)
        except Exception as e:
            print('PyQt6 import error:', str(e))
            import traceback; traceback.print_exc()
            sys.exit(1)
            
        # Test application import
        try:
            from smartcalc import main
            print('Successfully imported smartcalc')
        except Exception as e:
            print('Error importing smartcalc:', str(e))
            import traceback; traceback.print_exc()
            sys.exit(1)
        "
        
        # Run the application in test mode
        python -m smartcalc --test-mode
        
    - name: Run pytest
      run: |
        echo "=== Running pytest ==="
        pip install pytest pytest-qt
        python -m pytest tests/ -v
